# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
City.destroy_all
Business.destroy_all
User.destroy_all
Review.destroy_all
Like.destroy_all

u1 = User.create!(username: "Guest", password: 'password', city: 'Seattle, WA')


c1 = City.create!(name: "Seattle", lat: 47.6272905, lng: -122.3640454, image_url_one: 'https://s3.us-east-2.amazonaws.com/thelocallist/SeattleArt.png', image_url_two: 'https://s3.us-east-2.amazonaws.com/thelocallist/seattle2.png', tagline: "The Emerald City")
c2 = City.create!(name: "Portland", lat: 45.5435629, lng: -122.7948496, image_url_one: 'https://s3.us-east-2.amazonaws.com/thelocallist/PortlandArt.png',image_url_two: 'https://s3.us-east-2.amazonaws.com/thelocallist/seattle2.png', tagline: "The City of Roses")
c3 = City.create!(name: "San Francisco", lat: 37.7578149, lng: -122.5078119, image_url_one: 'https://s3.us-east-2.amazonaws.com/thelocallist/SanFranciscoArt.png', image_url_two: 'https://s3.us-east-2.amazonaws.com/thelocallist/seattle2.png', tagline: "The Golden City")
c4 = City.create!(name: "New York", lat: 40.7591703, lng: -74.0394428, image_url_one: 'https://s3.us-east-2.amazonaws.com/thelocallist/NewYorkArt.png', image_url_two: 'https://s3.us-east-2.amazonaws.com/thelocallist/seattle2.png', tagline: "The Empire City")
c5 = City.create!(name: "Austin", lat: 30.3079823, lng: -97.8938307, image_url_one: 'https://s3.us-east-2.amazonaws.com/thelocallist/AustinArt.png', image_url_two: 'https://s3.us-east-2.amazonaws.com/thelocallist/seattle2.png', tagline: "Waterloo")
c6 = City.create!(name: "Boston", lat: 42.3145151, lng: -71.2511577, image_url_one: 'https://s3.us-east-2.amazonaws.com/thelocallist/BostonArt.png', image_url_two: 'https://s3.us-east-2.amazonaws.com/thelocallist/seattle2.png', tagline: "The Puritan City")
c7 = City.create!(name: "Chicago", lat: 41.8339025, lng: -88.0128379, image_url_one: 'https://s3.us-east-2.amazonaws.com/thelocallist/ChicagoArt.png', image_url_two: 'https://s3.us-east-2.amazonaws.com/thelocallist/seattle2.png', tagline: "The Windy City")
c8 = City.create!(name: "Los Angeles", lat: 34.0537312, lng: -118.3788134, image_url_one: 'https://s3.us-east-2.amazonaws.com/thelocallist/LosAngelesArt.png', image_url_two: 'https://s3.us-east-2.amazonaws.com/thelocallist/seattle2.png', tagline: "La La Land")
c9 = City.create!(name: "Philadelphia", lat: 40.0026763, lng: -75.2584612, image_url_one: 'https://s3.us-east-2.amazonaws.com/thelocallist/PhiladelphiaArt.png', image_url_two: 'https://s3.us-east-2.amazonaws.com/thelocallist/seattle2.png', tagline: "The City of Brotherly Love")

b1 = Business.create!(city_id: c1.id,city_name: "Seattle", name: "Slate Coffee", lat: 47.6677577, lng: -122.3672629, youTubeUrl: 'https://www.youtube.com/watch?v=C0hLdZ9ueT8', imageFile1: 'https://s3.us-east-2.amazonaws.com/thelocallist/slate1.png', imageFile2: 'https://s3.us-east-2.amazonaws.com/thelocallist/slate2.png', imageFile3: 'https://s3.us-east-2.amazonaws.com/thelocallist/slate5.png', imageFile4: 'https://s3.us-east-2.amazonaws.com/thelocallist/slate4.png', imageFile5: 'https://s3.us-east-2.amazonaws.com/thelocallist/slate3.png', imageFile6: 'https://s3.us-east-2.amazonaws.com/thelocallist/slate1.png', imageFile7: 'https://s3.us-east-2.amazonaws.com/thelocallist/slate9.png', imageFile8: 'https://s3.us-east-2.amazonaws.com/thelocallist/slate8.png', description: 'Located in East Ballard, our coffee bar was our first permanent location. It has a neighborhood feel that invites you to stay awhile and get to know those sitting around you. We have a very simple menu offering hand-brewed coffee, espresso, espresso + milk, as well as pastries, tea, tasting flights, and an industry favorite: the deconstructed espresso + milk.', businessType: 'coffee', address: '5413 6th Ave NW Seattle, WA 98107', hours: 'Mon	7:00 am - 5:00 pm	Tue	7:00 am - 5:00 pm	Wed	7:00 am - 5:00 pm	Thu	7:00 am - 5:00 pm	Fri	7:00 am - 6:00 pm Sat	8:00 am - 6:00 pm	Sun	8:00 am - 5:00 pm	', phoneNumber:'(206) 240-7174', reservation: 'false',like_count: 25, overflow: false)
b2 = Business.create!(city_id: c1.id,city_name: "Seattle", name: "Stumptown Coffee", lat: 47.6120899, lng: -122.3189981, youTubeUrl: 'https://www.youtube.com/watch?v=C0hLdZ9ueT8', imageFile1: 'https://s3.us-east-2.amazonaws.com/thelocallist/stumptown1.png', imageFile7: 'https://s3.us-east-2.amazonaws.com/thelocallist/Stumptown2.png',imageFile3:'https://s3.us-east-2.amazonaws.com/thelocallist/Stumptown8.png', imageFile4: 'https://s3.us-east-2.amazonaws.com/thelocallist/Stumptown4.png',imageFile5:'https://s3.us-east-2.amazonaws.com/thelocallist/Stumptown5.png',imageFile6:'https://s3.us-east-2.amazonaws.com/thelocallist/Stumptown6.png',imageFile8:'https://s3.us-east-2.amazonaws.com/thelocallist/Stumptown3.png',  description: 'Opened in the fall of 2007, our 12th Avenue café is home to our Seattle roastery.In addition to a full espresso bar, drip coffee, brew-by-the-cup offerings and cold brew, you can enjoy beverages from Rachels Ginger Beer, Kombucha Town, and Steven Smith Tea as well as Ellenos yogurt and pastries from Fuji Bakery.', businessType: 'coffee', address: '1115 12th Ave, Seattle, WA 98122', hours: 'Mon	7:00 am - 5:00 pm	Tue	7:00 am - 5:00 pm	Wed	7:00 am - 5:00 pm	Thu	7:00 am - 5:00 pm	Fri	7:00 am - 6:00 pm Sat	8:00 am - 6:00 pm	Sun	8:00 am - 5:00 pm	', phoneNumber:'(855) 711-3385', reservation:'false', overflow: false)
b3 = Business.create!(city_id: c1.id,city_name: "Seattle", name: "Milstead Coffee", lat: 47.6493855, lng: -122.348876, youTubeUrl: 'https://www.youtube.com/watch?v=C0hLdZ9ueT8', imageFile1: 'https://s3.us-east-2.amazonaws.com/thelocallist/milstead1.png', imageFile2: 'https://s3.us-east-2.amazonaws.com/thelocallist/Milstead2.png', imageFile3: 'https://s3.us-east-2.amazonaws.com/thelocallist/Milstead3.png', imageFile4: 'https://s3.us-east-2.amazonaws.com/thelocallist/Milstead4.png', imageFile5: 'https://s3.us-east-2.amazonaws.com/thelocallist/Milstead5.png', imageFile6: 'https://s3.us-east-2.amazonaws.com/thelocallist/Milstead6.png', imageFile7: 'https://s3.us-east-2.amazonaws.com/thelocallist/Milstead7.png', imageFile8: 'https://s3.us-east-2.amazonaws.com/thelocallist/Milstead8.png', description: 'Before our baristas can craft your drink, highly skilled roasters must source and prepare beans from passionate farmers throughout the coffee belt. We feature fine coffees from renowned roasters Stumptown, Intelligentsia, and Coava.', businessType: 'coffee', address: '754 N 34th St, Seattle, WA 98103', hours: 'Mon	7:00 am - 6:00 pm	Tue	7:00 am - 6:00 pm	Wed	7:00 am - 6:00 pm	Thu	7:00 am - 6:00 pm	Fri	7:00 am - 6:00 pm Sat	8:00 am - 6:00 pm	Sun	8:00 am - 6:00 pm	', phoneNumber:'(206) 659-4814', reservation:false, overflow: false)
b4 = Business.create!(city_id: c1.id,city_name: "Seattle", name: "Walrus And The Carpenter", lat: 47.6635069, lng: -122.3813122, youTubeUrl: 'https://www.youtube.com/watch?v=C0hLdZ9ueT8', imageFile1: 'https://s3.us-east-2.amazonaws.com/thelocallist/walrus1.png',imageFile2: 'https://s3.us-east-2.amazonaws.com/thelocallist/walrus1.png', imageFile3: 'https://s3.us-east-2.amazonaws.com/thelocallist/Walrus2.png',imageFile4: 'https://s3.us-east-2.amazonaws.com/thelocallist/Walrus3.png', imageFile5: 'https://s3.us-east-2.amazonaws.com/thelocallist/Walrus4.png', imageFile6: 'https://s3.us-east-2.amazonaws.com/thelocallist/Walrus5.png', imageFile7: 'https://s3.us-east-2.amazonaws.com/thelocallist/walrus1.png', imageFile8: 'https://s3.us-east-2.amazonaws.com/thelocallist/Walrus7.png', description: 'Opened in 2010, The Walrus and The Carpenter marries restaurant to fishing pub. Tallboys, muscadet, piles of chubby oysters and smart plates are served in a lively, approachable space in Old Ballard.', businessType: 'restaurant', address: ' 4743 Ballard Ave NW, Seattle, WA 98107', hours: 'Mon	7:00 am - 6:00 pm	Tue	7:00 am - 6:00 pm	Wed	7:00 am - 6:00 pm	Thu	7:00 am - 6:00 pm	Fri	7:00 am - 6:00 pm Sat	8:00 am - 6:00 pm	Sun	8:00 am - 6:00 pm	', phoneNumber:'(206) 395-9227', reservation:false, overflow: false)
b5 = Business.create!(city_id: c1.id,city_name: "Seattle", name: "The Whale Wins", lat: 47.6495961, lng: -122.3445547, youTubeUrl: 'https://www.youtube.com/watch?v=C0hLdZ9ueT8', imageFile1: 'https://s3.us-east-2.amazonaws.com/thelocallist/whale1.png', imageFile3: 'https://s3.us-east-2.amazonaws.com/thelocallist/whale1.png', imageFile4: 'https://s3.us-east-2.amazonaws.com/thelocallist/whale2.png',imageFile5: 'https://s3.us-east-2.amazonaws.com/thelocallist/whale3.png',imageFile6: 'https://s3.us-east-2.amazonaws.com/thelocallist/whale4.png',imageFile7: 'https://s3.us-east-2.amazonaws.com/thelocallist/whale5.png',imageFile8: 'https://s3.us-east-2.amazonaws.com/thelocallist/whale6.png', description: 'The Whale Wins is the creation of chef Renee Erickson, Jeremy Price and Chad Dale — the folks behind Ballard’s acclaimed The Walrus and the Carpenter. Drawing inspiration from the cuisine of some of Renee Erickson’s favorite places in southern Europe and England, The Whale Wins’ menu features the very best foods from local beaches, gardens and farms.', businessType: 'restaurant', address: '3506 Stone Way N Seattle, WA 98103', hours: 'Mon	7:00 am - 6:00 pm	Tue	7:00 am - 6:00 pm	Wed	7:00 am - 6:00 pm	Thu	7:00 am - 6:00 pm	Fri	7:00 am - 6:00 pm Sat	8:00 am - 6:00 pm	Sun	8:00 am - 6:00 pm	', phoneNumber:'(206) 632-9425', reservation:'false', overflow: false)
b6 = Business.create!(city_id: c1.id,city_name: "Seattle", name: "Canon", lat: 47.6113135, lng: -122.3171179, youTubeUrl: 'https://www.youtube.com/watch?v=C0hLdZ9ueT8', imageFile1: 'https://s3.us-east-2.amazonaws.com/thelocallist/canon1.png', imageFile3: 'https://s3.us-east-2.amazonaws.com/thelocallist/canon1.png',imageFile4: 'https://s3.us-east-2.amazonaws.com/thelocallist/canon3.png',imageFile5: 'https://s3.us-east-2.amazonaws.com/thelocallist/canon4.png',imageFile6: 'https://s3.us-east-2.amazonaws.com/thelocallist/canon5.png',imageFile7: 'https://s3.us-east-2.amazonaws.com/thelocallist/canon6.png',imageFile8: 'https://s3.us-east-2.amazonaws.com/thelocallist/canon2.png', description: 'As if Canon  wasn’t hard enough to get in to on a Saturday night – now comes news that Seattle’s favorite cocktail den has been anointed one of the World’s Best Bars. The ranking is one of the most prestigious cocktail honors in Europe, and the highest accolade for Canon since it took home “World’s Best Drink Selection” at the Tales of the Cocktail.', businessType: 'bar', address: '928 12th Ave, Seattle, WA 98122', hours: 'Mon	7:00 am - 6:00 pm	Tue	7:00 am - 6:00 pm	Wed	7:00 am - 6:00 pm	Thu	7:00 am - 6:00 pm	Fri	7:00 am - 6:00 pm Sat	8:00 am - 6:00 pm	Sun	8:00 am - 6:00 pm', phoneNumber:'', reservation:'false', overflow: false)
b7 = Business.create!(city_id: c1.id,city_name: "Seattle", name: "Sun Liquor", lat: 47.6245773, lng: -122.3276671, youTubeUrl: 'https://www.youtube.com/watch?v=C0hLdZ9ueT8', imageFile1: 'https://s3.us-east-2.amazonaws.com/thelocallist/sunliquor1.png', imageFile3: 'https://s3.us-east-2.amazonaws.com/thelocallist/sunliquor1.png', imageFile4: 'https://s3.us-east-2.amazonaws.com/thelocallist/sunliquor2.png',imageFile5: 'https://s3.us-east-2.amazonaws.com/thelocallist/sunliquor3.png',imageFile6: 'https://s3.us-east-2.amazonaws.com/thelocallist/sunliquor4.png',imageFile7: 'https://s3.us-east-2.amazonaws.com/thelocallist/sunliquor5.png',imageFile8: 'https://s3.us-east-2.amazonaws.com/thelocallist/sunliquor6.png', description: 'At this small bar, the juice is fresh and the liquor is excellent. Sun Liquors aesthetic is sort of tiki, kind of stylized colonial Singapore, or maybe upscale Hong Kong Phooey. Every detail scrupulously aligns: antique cocktail glasses and shakers behind the bar, bamboo chairs and bamboo bowtie accents.', businessType: 'bar', address: '607 Summit Ave E, Seattle, WA 98102', hours: 'Mon	7:00 am - 6:00 pm	Tue	7:00 am - 6:00 pm	Wed	7:00 am - 6:00 pm	Thu	7:00 am - 6:00 pm	Fri	7:00 am - 6:00 pm Sat	8:00 am - 6:00 pm	Sun	8:00 am - 6:00 pm	', phoneNumber:'(206) 860-1130', reservation:'false', overflow: false)
b8 = Business.create!(city_id: c1.id,city_name: "Seattle", name: "The Pink Door", lat: 47.6103688, lng: -122.3431129, youTubeUrl: 'https://www.youtube.com/watch?v=C0hLdZ9ueT8', imageFile1: 'https://s3.us-east-2.amazonaws.com/thelocallist/pinkdoor1.png', imageFile2: 'a', description: 'Along the quaint Post Alley at Seattle’s Pike Place Market awaits one of the city’s most beloved restaurant destinations since 1981: The Pink Door. Equal parts Italian-American dining, eclectic entertainment and spirited service.', businessType: 'restaurant', address: 'a', hours: 'a', phoneNumber:'a', reservation:'false', overflow: false)
b10 = Business.create!(city_id: c1.id,city_name: "Seattle", name: "The Pine Box", lat: 47.6154952, lng: -122.329865, youTubeUrl: 'https://www.youtube.com/watch?v=C0hLdZ9ueT8', imageFile1: 'https://s3.us-east-2.amazonaws.com/thelocallist/pinebox1.png', imageFile2: 'a', description: 'We are proud to be a part of our Capitol Hill community. Built in 1923, this colonial-style building of vaulted ceilings and glass windows was once the new expansion of E.R. Butterworth & Sons Family Funeral Business.', businessType: 'bar', address: 'a', hours: 'a', phoneNumber:'a', reservation:'false', overflow: false)
b9 = Business.create!(city_id: c1.id,city_name: "Seattle", name: "Morsel", lat: 47.6646567, lng: -122.3151579, youTubeUrl: 'https://www.youtube.com/watch?v=C0hLdZ9ueT8', imageFile1: 'https://s3.us-east-2.amazonaws.com/thelocallist/morsel1.png', imageFile2: 'a', description: 'Giant, cloudlike biscuits are Morsels specialty; their “Cheesy Biscuit” with roasted tomato jam is what garlic bread wishes it could be. And their cappuccino, made with local Veltons Mexico Nayarita coffee and Twin Brook Creamery milk, is way better than most coffee drinks, even in this land of high-quality coffee.There is also house-made bacon jam and sandwiches.', businessType: 'restaurant', address: 'a', hours: 'a', phoneNumber:'a', reservation:'false', overflow: false)

b11 = Business.create!(city_id: c2.id,city_name: "Portland", name: "Bible Club", lat: 47.6677577, lng: -122.3672629, youTubeUrl: 'https://www.youtube.com/watch?v=C0hLdZ9ueT8', imageFile1: 'https://s3.us-east-2.amazonaws.com/thelocallist/bible1.png', imageFile3: 'https://s3.us-east-2.amazonaws.com/thelocallist/bible1.png',imageFile4: 'https://s3.us-east-2.amazonaws.com/thelocallist/bible5.png',imageFile5: 'https://s3.us-east-2.amazonaws.com/thelocallist/bible3.png',imageFile6: 'https://s3.us-east-2.amazonaws.com/thelocallist/bible4.png',imageFile7: 'https://s3.us-east-2.amazonaws.com/thelocallist/bible2.png',imageFile8: 'https://s3.us-east-2.amazonaws.com/thelocallist/bible6.png', description: 'Inside, almost everything, from the portraits of presidents to the juicers and corkscrews the bartenders use, is American-made before 1930. It is sort of like stepping into your great grandparents house.', businessType: 'bar', address: '6716 SE 16th Ave, Portland, OR 97202', hours: 'Mon	7:00 am - 6:00 pm	Tue	7:00 am - 6:00 pm	Wed	7:00 am - 6:00 pm	Thu	7:00 am - 6:00 pm	Fri	7:00 am - 6:00 pm Sat	8:00 am - 6:00 pm	Sun	8:00 am - 6:00 pm	', phoneNumber:'(971) 279-2198', reservation:'false', overflow: false)
b12 = Business.create!(city_id: c2.id,city_name: "Portland", name: "Heart Coffee", lat: 45.5214755, lng: -122.6860698, youTubeUrl: 'https://www.youtube.com/watch?v=C0hLdZ9ueT8', imageFile1: 'https://s3.us-east-2.amazonaws.com/thelocallist/Heart1.png', imageFile3: 'https://s3.us-east-2.amazonaws.com/thelocallist/Heart1.png', imageFile4: 'https://s3.us-east-2.amazonaws.com/thelocallist/Heart2.png', imageFile5: 'https://s3.us-east-2.amazonaws.com/thelocallist/Heart3.png', imageFile6: 'https://s3.us-east-2.amazonaws.com/thelocallist/Heart4.png', imageFile7: 'https://s3.us-east-2.amazonaws.com/thelocallist/Heart5.png', imageFile8: 'https://s3.us-east-2.amazonaws.com/thelocallist/Heart6.png', description: 'The motivation behind our coffee is simple: uncompromising quality. We are a specialty coffee roasting company aiming to bring people a focused and an exceptional coffee experience. We begin with some of the best green coffee from mainly Central America, South America, and Africa.', businessType: 'coffee', address: '5181 SE Woodstock Blvd, Portland, OR', hours: 'Mon	7:00 am - 6:00 pm	Tue	7:00 am - 6:00 pm	Wed	7:00 am - 6:00 pm	Thu	7:00 am - 6:00 pm	Fri	7:00 am - 6:00 pm Sat	8:00 am - 6:00 pm	Sun	8:00 am - 6:00 pm	', phoneNumber:'(503) 224-0036', reservation:'false', overflow: false)
b13 = Business.create!(city_id: c2.id,city_name: "Portland", name: "Coava Coffee", lat: 47.6677577, lng: -122.3672629, youTubeUrl: 'https://www.youtube.com/watch?v=C0hLdZ9ueT8', imageFile1: 'https://s3.us-east-2.amazonaws.com/thelocallist/stumptown1.png', imageFile2: 'a', description: 'a', businessType: 'coffee', address: 'a', hours: 'a', phoneNumber:'a', reservation:'false', overflow: false)
b14 = Business.create!(city_id: c2.id,city_name: "Portland", name: "Tov", lat: 47.6677577, lng: -122.3672629, youTubeUrl: 'https://www.youtube.com/watch?v=C0hLdZ9ueT8', imageFile1: 'https://s3.us-east-2.amazonaws.com/thelocallist/stumptown1.png', imageFile2: 'a', description: 'a', businessType: 'coffee', address: 'a', hours: 'a', phoneNumber:'a', reservation:'false', overflow: false)
b15 = Business.create!(city_id: c2.id,city_name: "Portland", name: "Willow", lat: 47.6677577, lng: -122.3672629, youTubeUrl: 'https://www.youtube.com/watch?v=C0hLdZ9ueT8', imageFile1: 'https://s3.us-east-2.amazonaws.com/thelocallist/stumptown1.png', imageFile2: 'a', description: 'a', businessType: 'coffee', address: 'a', hours: 'a', phoneNumber:'a', reservation:'false', overflow: false)
b16 = Business.create!(city_id: c2.id,city_name: "Portland", name: "Tasty n Alder", lat: 45.5213443, lng: -122.6856714, youTubeUrl: 'https://www.youtube.com/watch?v=C0hLdZ9ueT8', imageFile1: 'https://s3.us-east-2.amazonaws.com/thelocallist/tasty1.png', imageFile2: 'a', description: 'When our brunch service ends at 2pm we welcome our guests to stop by in person to add their name to our waiting list for the 5:30pm dinner seating. Our midday bar menu is available from 2pm-5:30pm in the bar. ', businessType: 'restaurant', address: '580 SW 12TH Ave, Portland, Oregon 97205', hours: 'Mon	7:00 am - 6:00 pm	Tue	7:00 am - 6:00 pm	Wed	7:00 am - 6:00 pm	Thu	7:00 am - 6:00 pm	Fri	7:00 am - 6:00 pm Sat	8:00 am - 6:00 pm	Sun	8:00 am - 6:00 pm	', phoneNumber:'(503)621-9251', reservation:'false', overflow: false)
b17 = Business.create!(city_id: c2.id,city_name: "Portland", name: "Teardrop Cocktail", lat: 47.6677577, lng: -122.3672629, youTubeUrl: 'https://www.youtube.com/watch?v=C0hLdZ9ueT8', imageFile1: 'https://s3.us-east-2.amazonaws.com/thelocallist/teardrop1.png', imageFile2: 'a', description: 'Pioneering the cocktail renaissance since 2007, Teardrop Cocktail Lounge offers lovingly made libations in the heart of Portlands Pearl District. From a profound respect for the classics to the adventure of unique flavor combinations, ours is a perpetual quest for the new frontier of the cocktail. ', businessType: 'bar', address: '1015 NW Everett St, Portland, OR 97209', hours: 'Mon	7:00 am - 6:00 pm	Tue	7:00 am - 6:00 pm	Wed	7:00 am - 6:00 pm	Thu	7:00 am - 6:00 pm	Fri	7:00 am - 6:00 pm Sat	8:00 am - 6:00 pm	Sun	8:00 am - 6:00 pm	', phoneNumber:'(503) 445-8109', reservation:'false', overflow: false)
b18 = Business.create!(city_id: c2.id,city_name: "Portland", name: "Multnomah Whiskey Library", lat: 47.6677577, lng: -122.3672629, youTubeUrl: 'https://www.youtube.com/watch?v=C0hLdZ9ueT8', imageFile1: 'https://s3.us-east-2.amazonaws.com/thelocallist/stumptown1.png', imageFile2: 'a', description: 'a', businessType: 'coffee', address: 'a', hours: 'a', phoneNumber:'a', reservation:'false', overflow: false)
b19 = Business.create!(city_id: c2.id,city_name: "Portland", name: "Screen Door", lat: 47.6677577, lng: -122.3672629, youTubeUrl: 'https://www.youtube.com/watch?v=C0hLdZ9ueT8', imageFile1: 'https://s3.us-east-2.amazonaws.com/thelocallist/stumptown1.png', imageFile2: 'a', description: 'a', businessType: 'coffee', address: 'a', hours: 'a', phoneNumber:'a', reservation:'false', overflow: false)
b20 = Business.create!(city_id: c2.id,city_name: "Portland", name: "Barista", lat: 47.6677577, lng: -122.3672629, youTubeUrl: 'https://www.youtube.com/watch?v=C0hLdZ9ueT8', imageFile1: 'https://s3.us-east-2.amazonaws.com/thelocallist/stumptown1.png', imageFile2: 'a', description: 'a', businessType: 'coffee', address: 'a', hours: 'a', phoneNumber:'a', reservation:'false', overflow: false)


r1 = Review.create!(body: "Hands down the best coffee shop in Seattle.  The 8 oz espresso with milk made my cry one time.  Also highly recommend the deconstructed espresso with milk.  If you're lucky, you might also run into the neighborhood Slate cat!", recommended:true, user_id: u1.id, business_id: b1.id)
r2 = Review.create!(body: "Yes.  The 8 oz espresso with milk made my cry one time.  Also highly recommend the deconstructed espresso with milk.  If you're lucky, you might also run into the neighborhood Slate cat!", recommended:true, user_id: u1.id, business_id: b1.id)
r3 = Review.create!(body: "This place is honestly legendary..Except for the fact that it took me a year of trying to come here before I could even get inside the bar.  The lines are hysterical.  There's sort of a cult following for this place.  And I don't like cults.", recommended:true, user_id: u1.id, business_id: b6.id)

l1 = Like.create!(user_id: u1.id, business_id: b1.id)
